### ISSUE TITLE
After updating, commands are interpreted as direct messages

### ISSUE THREAD

**Issue by Roy-Orbison** [scottleedavis/mattermost-plugin-remind#162] opened 2019-08-29 04:53 UTC
#### Summary
After updating, commands typed into the DM chat of remindbot and myself were interpreted as direct messages to remindbot.

#### Steps to reproduce
1. Update Mattermost/Remind Bot
2. Go to remindbot's DM chat
3. Send `/remind list`
4. Hangs chat

#### Expected behavior
Normal command response

#### Observed behavior (that appears unintentional)
A `Loading…` message in the middle of the screen.

#### Server configuration
**Operating system:** Debian

**Mattermost version:** 5.14.1

**Matterpoll version:** ???

**Remind Bot version:** 0.4.4

**Updated from an older Remind bot version or fresh install:** Updated

#### Additional context
Going to another chat window and doing the command there worked, then after that commands in the remindbot DM chat worked again.

**Comment by scottleedavis** [comment] 2019-08-29 05:24
Very strange.  I am not able to replicate the `Loading...` hang.  It sounds like it was a one time issue, though I am curious as what the root cause might be.   have you reproduced this more than once?

**Comment by Roy-Orbison** [comment] 2019-08-29 05:33
I got the same error a few times until I invoked the bot in another window, and now it works as expected. I don't really fancy downgrading everything and restoring from backup just to see if it happens again. Given that it self-resolved, I doubt it's critical, but thought you might want to know.

**Comment by scottleedavis** [comment] 2019-08-29 05:48
being able to search this issue in closed issues will help troubleshoot if it happens again, though for now I will close it.  I appreciate the heads up.  It always helps.

**Closed by scottleedavis** 2019-08-29 05:48 UTC
Labels: triage
