### ISSUE TITLE
/remind @username "Test Reminder" in 1 minute not working correctly

### ISSUE THREAD

**Issue by JtheBAB** [scottleedavis/mattermost-plugin-remind#62] opened 2019-04-17 10:24 UTC
Hi Scott

When someone types

/remind @username "Test Reminder" in 1 minute

i get this confirmation:

I will remind @username "Test Reminder" in 1 minute at 12:20PM today.

But then i got the reminder message and not the @username.

Best regards

JtheBAB

**Comment by hanzei** [comment] 2019-04-17 10:44
Technically speak the problem is, that bot accounts can't create ephemeral posts. Setting the user name and user icon manually doesn't seam ideal.

I opened a discussion at https://community.mattermost.com/core/pl/4t54caacc3b978irq3u86qnfsr

**Comment by scottleedavis** [comment] 2019-04-18 05:45
Thanks @JtheBAB for finding this!   This bug is fixed in release 0.1.3.  :)

https://github.com/scottleedavis/mattermost-plugin-remind/releases/tag/v0.1.3

**Closed by scottleedavis** 2019-04-18 05:45 UTC
Labels: bug
