### ISSUE TITLE
None of the buttons respond

### ISSUE THREAD

**Issue by ewwollesen** [scottleedavis/mattermost-plugin-remind#120] opened 2019-06-11 16:07 UTC
This is, I guess, similar to #93 and #100, but in our production environment the plugin works, but none of the buttons such as "mark as complete", "view reminders", or "delete" do anything. Here is the error we get in the logs:

```json
{"level":"error","ts":1560267803.0034556,"caller":"mlog/log.go:172","msg":"Action integration error","path":"/api/v4/posts/eape9ea1afyzigpp1zi9r8ykuh/actions/rzmus74sb78xfdu5nqrmnbe6ur","request_id":"8kskz569m3bpug75y5i791uidh","ip_addr":"redacted","user_id":"guosn45uo7rd7bzigt9xqbseco","method":"POST","err_where":"DoActionRequest","http_code":400,"err_details":"err=Post http://chat.ssctech.com/plugins/com.github.scottleedavis.mattermost-plugin-remind/delete/ephemeral: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
```

We're running MM version 5.10.1 running on RHEL and plugin version 0.3.1. What's interesting is that is works fine in our test environment, and both prod and test are set up pretty similarly. At least in terms of Mattermost configuration. It also doesn't work from the web page, android, or desktop client.

**Comment by scottleedavis** [comment] 2019-06-12 07:15
@ewwollesen As the error looks to be a timeout on the request, I suspect something different setup for the network/firewall that may be 'sinking' the plugin button callback to `http://chat.ssctech.com/plugins/com.github.scottleedavis.mattermost-plugin-remind/*`.  That is my hunch and may not be correct, though in hearing you say that the test environment works I am curious to know what exactly is stopping the plugin post action.  

do other button/interactive plugins work?   (e.g. matterpoll)

**Comment by ewwollesen** [comment] 2019-06-12 13:44
We don't use any other plugins (yet) so I can't confirm that. I had the same suspicion that it's something on our firewall or load balancer that's causing it, but sometimes those guys can be difficult to engage and get help from. I'll talk to them and see if there are any differences in configuration between test and prod on that end and get back with you.

**Comment by sushil-akkawar** [comment] 2019-06-18 10:39
Today morning, I have upgraded my Mattermost to 5.12.0 from an old version on which the Matterpoll and remind plugin do not work.
I installed both of 'em after upgrading to 5.12.0 and facing the same above mentioned issue.

> do other button/interactive plugins work? (e.g. matterpoll)

I can confirm the click-buttons are not working in both the said plugins.
In the Mattermost logs, I found this,

`{"level":"error","ts":1560850581.1029434,"caller":"mlog/log.go:172","msg":"Action integration error","path":"/api/v4/posts/xxxxxxxxxxxxxxxxxxxx/actions/xxxxxxxxxxxxxxxx","request_id":"xxxxxxxxxxxxxxxxx","ip_addr":"XX.XX.XXX.XXX","user_id":"xxxxxxxxxxxxxxxxxxx","method":"POST","err_where":"DoActionRequest","http_code":400,"err_details":"err=Post https://mattermost.example.com/plugins/com.github.scottleedavis.mattermost-plugin-remind/view/ephemeral: x509: certificate signed by unknown authority"}`

I tried to find some solutions, but didn't find any helpful one.
By the way I am using Mattermost on Ubuntu 14.04.
Thanks

**Comment by sushil-akkawar** [comment] 2019-06-18 10:46
@ewwollesen 
I tried to solve above issue using https://manuals.gfi.com/en/kerio/connect/content/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html
Not successful yet. I am using Let's Encrypt SSL.

**Comment by scottleedavis** [comment] 2019-06-18 15:33
@hanzei if you have time, have you seen either the timeout or certificate issues before with matterpoll?  This issue is apparently happening on both remind and matterpoll.  I still feel timeout is caused by a network configuration and the certificate error is a self signed cert issue however open to digging deeper if there is something we can do.

**Comment by hanzei** [comment] 2019-06-19 09:46
People have run into the certificate issue a couple of times with Matterpoll. Every time this was caused by a self signed certificate that the server didn't trust.

I've never had issues with a timeout. I agree with the assumption that the issue is caused by the firewall or load balancer.

**Comment by sushil-akkawar** [comment] 2019-06-19 09:50
@hanzei Thanks for giving some clues about the issue. I would like to know you that I have issued the Let's Encrypt SSL for Mattermost using the certbot tool. It would be great if you suggest some references or give some tips on fixing it.
Advance thanks.

**Comment by hanzei** [comment] 2019-06-19 09:56
Are you using the "build" in Let's Encrypt solution from Mattermost or another tool?

**Comment by sushil-akkawar** [comment] 2019-06-19 10:22
I am not using the "build" in Let's Encrypt solution from Mattermost.

**Comment by hanzei** [comment] 2019-06-19 10:29
What is the output if you just run `curl $YOUR_MATTERMOST_URL`?

**Comment by sushil-akkawar** [comment] 2019-06-19 10:38
@hanzei and @scottleedavis 
I just set 'true' for 'Forward80To443', restarted the server.
Then visited the Mattermost URL, there was something like 'Proxy error', then I reverted the config.json and restarted the server again, seems like the buttons are working now.
Then I created a few reminders and it is absolutely working fine for me (I have System Admin role assigned to me). I asked my colleague to create reminders and try clicking on the buttons, it is not working for her.
Is there any access levels available in remind plugin? Because I am getting below error message when she clicks on any button.

`{"level":"error","ts":1560940254.8299675,"caller":"mlog/log.go:172","msg":"You do not have the appropriate permissions","path":"/api/v4/posts/64btw6r6hbfdawdewbg46p3tfek3c/actions/rxyf3bn4n7rp5jyjqzh33kk1mc","request_id":"XXXXXXXXXXXXXXXXXXX","ip_addr":"XX.XXX.XXX.XX","user_id":"XXXXXXXXXXXXXX","method":"POST","err_where":"Permissions","http_code":403,"err_details":"userId=xxxxxxxxxxxxxxxxxxxx, permission=read_channel"}`

**Comment by sushil-akkawar** [comment] 2019-06-19 10:42
> What is the output if you just run `curl $YOUR_MATTERMOST_URL`?

sushil@ip-XX-XX-XX-XX:~$ curl https://mattermost.example.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by scottleedavis** [comment] 2019-06-20 00:53
@sushil-akkawar there are no access levels in the remind plugin.  On a test 5.12 I run the remind command and buttons for both system admin and normal roles with our issue.  I am curious about the permissions issue.  Do matterpoll buttons work for your colleague?

**Comment by sushil-akkawar** [comment] 2019-06-20 10:19
> Do matterpoll buttons work for your colleague?

Yes. The buttons are working fine for both the plugins. We have no idea how it is resolved.
I will try to reproduce the permissions issue when I get the time and will update you if found anything useful.
Thanks

**Comment by scottleedavis** [comment] 2019-06-20 15:30
Please let us know if you're issue is resolved too @ewwollesen

**Comment by ewwollesen** [comment] 2019-06-20 15:37
> Please let us know if your issue is resolved too @ewwollesen

I'm the guy that opens an issue and then goes on vacation shortly after. We checked the F5 configuration between prod and test, and didn't see any differences there that would cause the issue. When I get back from PTO next week we'll do some tcpdumps and stuff and try to get a better handle on what's going on. Sorry for the delay.

**Comment by scottleedavis** [comment] 2019-07-11 01:45
Happy to help @ewwollesen if there are still issues though I'd like to close this if everything is working.

**Comment by scottleedavis** [comment] 2019-08-06 03:31
closing due to inactivity

**Closed by scottleedavis** 2019-08-06 03:31 UTC
Labels: question

**Comment by ewwollesen** [comment] 2019-09-26 19:27
Sorry to reopen this, and I know it's super old, but I wanted to provide an update in case others were having this issue. I FINALLY got time to really dig in to this and figure it out and it was actually fairly simple. **Basically the individual application servers (we run a 3 node cluster) didn't have firewall access to talk to the VIP on the load balancer.**

What's interesting is that since opening the issue we upgraded from 5.10 to 5.14 and installed v0.4.4 of the plugin and the error was slightly different and a little more useful. The original error was `com.github.scottleedavis.mattermost-plugin-remind/delete/ephemeral: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}` but after the upgrades it changed to `com.github.scottleedavis.mattermost-plugin-remind/delete: dial tcp <ip>:443: i/o timeout"`. That led me to just run a simple telnet <ip> 443 test from the app server and that didn't work either, so the network team checked the firewall and sure enough it was blocked. The opened that up and now everything is working.
